test-rai:
	cd minimal; ./build-docker.sh; ./run-docker.sh /root/local/docker/scripts/test-rai.sh

test-rai-python:
	cd minimal; ./build-docker.sh; ./run-docker.sh /root/local/docker/scripts/test-rai-python.sh



.NOTPARALLEL:
